### ISSUE TITLE
Missing expression prop. in getContent function

### ISSUE THREAD

**Issue by vaibhav-toddleapp** [3axap4eHko/react-native-katex#18]
https://github.com/3axap4eHko/react-native-katex/blob/918e131a88c57e2fa28472e8dfb9d0e12b70006f/src/index.tsx#L95
I guess you missed to pass `expression` prop in `getContent` function. which results blank webview.
@3axap4eHko

**Comment by 3axap4eHko** [comment]
I'm not sure what do you exactly mean. Currently [EXPO Snack](https://snack.expo.dev/@3axap4ehko/react-native-katex) works as expected without any problem.

**Comment by vaibhav-toddleapp** [comment]
What i mean is, you are not passing expression in getContent function argument but using it inside the function.

Also expo is cached. Try to change dependecy version to latest value it will throw error as well.

**Comment by 3axap4eHko** [comment]
@vaibhav-toddleapp thanks, I didn't know it cached
