### ISSUE TITLE
Why expression is using single backslash ?

### ISSUE THREAD

**Issue by akash-cp** [3axap4eHko/react-native-katex#3]
For web, we can render math expression as follows
`katex.render("c = \\pm\\sqrt{a^2 + b^2}", element);`

It uses double backslash, whereas for this package it uses single backslash, as follows
```
<Katex
  expression="c=\pm\sqrt{a^2 + b^2}"
/>
```
If I pass expression with double backslash it gives katex parse error.

I want to save my expression in a standard format and render it both on mobile and web.

Any type of help is hugely appreciated.

**Comment by ornitorrincco** [comment]
You only need to save the only single backslash format, and use regex for preproccess the string and add a backslash in the string.

**Comment by 3axap4eHko** [comment]
that is jsx syntax
