### ISSUE TITLE
Some information

### ISSUE THREAD

**Issue by Angelk90** [3axap4eHko/react-native-katex#6]
@3axap4eHko : 
Hi, I tried the module seems not to work on snack.expo.io.
Link: https://snack.expo.io/r1MkCYbGm

**Comment by mrded** [comment]
I'm experiencing the same problem. Cannot even import the library into react native expo project.

Example: https://snack.expo.io/ry6CnboUQ

p.s. The issue title probably needs an update. It's not clear what the problem is about.

**Comment by mrded** [comment]
I managed to copy an error:

> ReferenceError: [BABEL] react-native-katex/dist/index.js: Unknown option: /node_modules/react/react.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.
> 
> A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:
> 
> Invalid:
>   `{ presets: [{option: value}] }`
> Valid:
>   `{ presets: [['presetName', {option: value}]] }`

**Comment by mrded** [comment]
> > ReferenceError: [BABEL] react-native-katex/dist/index.js: Unknown option: /node_modules/react/react.js.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.> > A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:> > Invalid:>   `{ presets: [{option: value}] }`> Valid:>   `{ presets: [['presetName', {option: value}]] }`

**Comment by 3axap4eHko** [comment]
Please follow the example expo snack provided in the readme
