### ISSUE TITLE
Any way to render styled katex after the initial `window.onload`?

### ISSUE THREAD

**Issue by azanli** [3axap4eHko/react-native-katex#8]
Currently the only way to render an expression that is styled correctly is to hard-code the string into the props of the compoent. I.e.,

        <Katex
          expression="c=\pm\sqrt{a^2 + b^2}"
          ...
        />
but when I attempt to apply the expression dynamically like so,

        <Katex
          expression={this.state.expression}
          ...
        />
along with tweaking the `index.js` of this library to re-render the html content or call `window.location.reload()`, the new expression renders but the styling isn't applied.

How come `katex.render(expression, document.body, options)` doesn't apply styling on subsequent calls after the initial render? Having this fixed would essentially make this library complete. Are there any ideas on other DOM methods we can apply to the WebView/embedded HTML/CSS to  make this work?

**Comment by nolife08021** [comment]
@Friendly-Robot  did you find out any solution for this?

**Comment by azanli** [comment]
@nolife08021 Looks like Ian Swain, author of the Medium publication, [_Displaying KaTeX in React Native_](https://medium.com/@flankstaek/displaying-katex-in-react-native-9655c2628a7d) responded to my comment on this question. However, I did not test his suggestion as we skipped that implementation for other pressing ones at the time of the comment, now I'm with another company. Yet, I do remember randomly testing what he had suggested before he suggested it to me and (do not take my word for it) it did not work for me. Perhaps you will be better armed! Please let me know if it works for you!

Edit: Include link and tag
